language: node_js
node_js:
- '6'
sudo: required
services:
- mongodb
before_script:
- npm install grunt-cli -g
env:
- MONGODB_URL=mongodb://127.0.0.1:27017/aws
script:
- grunt test
deploy:
  provider: heroku
  api_key:
    secure: aohQjv9ap5Ru+Z85+/n0XMsP9hHiBCkw/TH1rLyWSovRV5aViqzfte6VOVe3p7+TjZflB1gzP4/2ojMb8CH5Tx9SRZnJFSuYqcJ+itQOjcBb5aLOnKGm915zLTtnuUp6S+OjVPtsaikmvBBeigSKAXXc1HFm2ZnRBYckZHR+9ojh+PqIv0DOFmxxzmm6+IppM6ZaVfSCV0Xu7Zvp2QlJcBpTSUR19o07epuRHZLJ2jAPorO0ktpp9ZKqzsTnQauf7rRwrMWPMseFWyZOuhhX2r5wyVZ4hR5FoDG14CulUSVfFM2N36UvkZ/wOrK0WuvVXjGIc+QNuUUe7UbFGATfYkHebJ3/lXGgEgjYzQVFviffqPNiiUU7XsX5ML/o8MH93Eu1M1P6WKFVdC2r0MowL6KSuZ/fxmBzldC+0VZl0s0DkzxMvg7TNUWxb/Fuios84BKL0K+Q4TG/ABheMuwpgKYS0ue9jlrm4IW5JNIXAm5NOnVGvnjS0JE1uFah2KFo9wB4WVWZYU3yJDbpRTjEv2fTeRQ2GFmZXw51oHOCYqPUM/UgXhniDA2TTUd8SUE8Tv7ba1cuGWbNbLHunYPbT+WBR6Z4S532/fBdxsfJ+i+9ZYijZUl/v6St6ZukfrGqZVIsMispoaIpeYpxzvEhxjLZZVY4SDVYflxr7/4oBSw=
  app: aws1617-jrl
  on:
    repo: Javirln/AWS-2017-sandbox
